# Welcome to Jekyll!

# Website settings
title: Intelligent Visual Computing Laboratory (iVCL)
# description: 
  # 

# description: Jack's blog,use Jekyll and github pages.
# keywords: Jack,Jalpc,blog,Jekyll,github,gh-pages
baseurl:  /web # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://tmquan.github.io/web  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /web/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Tran Minh Quan  # Be used at blog posts' author.
  first_name: Tran Minh Quan  # Be used at index page about me section.
  last_name: 진선미  # Be used at index page about me section.
  avatar: /static/assets/img/landing/gpgpu.jpg  # upload your avatar at directory and edit it.
  github_username: tmquan  # Leave blank if you don't have now
  linkedin_id: tmquan2090 # Leave blank if you don't have now
  google_scholar_id: 1kx2NrUAAAAJ # Leave blank if you don't have now
  # facebook_username: jiakunnj  # Leave blank if you don't have now
  # twitter_username: jiakun614  # Leave blank if you don't have now
  email: quantm88@gmail.com  # Leave blank if you don't have now
  # cv: http://cv.jarrekk.com  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  # skill_icon1:
  #   - name: icon-apache
  #   - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: fa-python
    - name: fa-github
    - name: icon-apache
  desc: >
      He is currently an affiliated lecturer at VinUniversity, a member of VinGroup, the largest enterprise in Vietnam by capitalization.
      
      He got a B.S. degree in Electrical Engineering at KAIST (2012) and received a Ph.D. degree in Computer Science, under the guidance of Professor Won-Ki Jeong, focused on GPU Computing, at UNIST (2019), both from South Korea. His research interests are image-to-image translation, inverse problems, and high-performance visual computing, specializing in biomedical image processing and applications. 

      He was one of the first students in High-performance Visual Computing Lab (the first CUDA research center in Korea), guided by Professor Won-Ki Jeong, who has moved to Korea University. 
      
      His domain of image modalities concentrates on X-ray, CT, MRI, and Electron Microscopy. All are centered around using GPU-accelerated computing to understand biomedical image data. His most notable work includes undersampled MRI reconstruction using a GAN-based deep neural network, which is one of the pioneering works in the MRI community using deep learning (Google scholar citation ~400 since 2018). This work demonstrated that compressed sensing theory maps well to a generative model using cyclic loss. He has published many research papers in top-tier venues, including Nature, IEEE Trans. Medical Imaging, IEEE Trans. Visualization and Computer Graphics, IEEE Trans. Parallel and Distributed Systems, Medical Image Analysis; and prestigious peer-reviewed conferences such as MICCAI, IEEE ISBI, IEEE CVPR, ISMRM, etc. He is a recipient of the NAVER graduate fellowship.
      
      Recently, he has been working on Deep learning-based Generative Adversarial Networks on various problems (neural volume rendering, variationally reconstructed radiographs, anatomical graphs). He also serves as a technical reviewer for NeuroComputing, IEEE Transactions, other journals, and conferences. He is a member of the AI Consultant Committee of Ho Chi Minh City, Vietnam. 

# # comment
# disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
#   name: jalpc

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: G-B4DLH79M37

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


theme: jekyll-theme-architect